# Generated by Django 5.0.4 on 2024-08-23 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analisiscus10fes10mos10',
            name='muestra',
        ),
        migrations.RemoveField(
            model_name='analisiscus4fes4mos4',
            name='muestra',
        ),
        migrations.RemoveField(
            model_name='analisiscuscusfe',
            name='muestra',
        ),
        migrations.RemoveField(
            model_name='analisiscutestconsh',
            name='muestra',
        ),
        migrations.RemoveField(
            model_name='analisiscutfezn',
            name='muestra',
        ),
        migrations.RemoveField(
            model_name='analisismulti',
            name='muestra',
        ),
        migrations.RemoveField(
            model_name='resultado',
            name='muestra',
        ),
    ]
