# Generated by Django 5.0.4 on 2024-09-19 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_new_user',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
