# Generated by Django 5.0.4 on 2024-10-07 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_metodoanalisis_cliente_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='metodoanalisis',
            name='unique_metodo_por_cliente',
        ),
    ]
