# Generated by Django 5.0.4 on 2024-10-07 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_metodoanalisis_unique_metodo_por_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='odt',
            name='Comentarios',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='odt',
            name='Prefijo',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Muestra inicial'),
        ),
    ]
